<?php
class Education {
    public function getCurriculum() {
        return [
            [
                'number' => 1,
                'discipline' => 'Экология',
                'department' => 'БЖ',
                'total_hours' => 54,
                'auditory_hours' => 27,
                'lectures' => 18,
                'labs' => 0,
                'practicals' => 9,
                'self_work' => 27,
            ],
            [
                'number' => 2,
                'discipline' => 'Высшая математика',
                'department' => 'ВМ',
                'total_hours' => 540,
                'auditory_hours' => 282,
                'lectures' => 141,
                'labs' => 0,
                'practicals' => 141,
                'self_work' => 258,
            ],
            [
                'number' => 3,
                'discipline' => 'Русский язык и культура речи',
                'department' => 'НГиГ',
                'total_hours' => 108,
                'auditory_hours' => 54,
                'lectures' => 18,
                'labs' => 0,
                'practicals' => 36,
                'self_work' => 54,
            ],
            [
                'number' => 4,
                'discipline' => 'Основы дискретной математики',
                'department' => 'ИС',
                'total_hours' => 216,
                'auditory_hours' => 139,
                'lectures' => 87,
                'labs' => 0,
                'practicals' => 52,
                'self_work' => 77,
            ],
            [
                'number' => 5,
                'discipline' => 'Основы программирования и алгоритмические языки',
                'department' => 'ИС',
                'total_hours' => 405,
                'auditory_hours' => 210,
                'lectures' => 105,
                'labs' => 87,
                'practicals' => 18,
                'self_work' => 195,
            ],
            [
                'number' => 6,
                'discipline' => 'Основы экологии',
                'department' => 'ПЭОП',
                'total_hours' => 54,
                'auditory_hours' => 27,
                'lectures' => 18,
                'labs' => 0,
                'practicals' => 9,
                'self_work' => 27,
            ],
            [
                'number' => 7,
                'discipline' => 'Теория вероятностей и математическая статистика',
                'department' => 'ИС',
                'total_hours' => 162,
                'auditory_hours' => 72,
                'lectures' => 54,
                'labs' => 18,
                'practicals' => 0,
                'self_work' => 90,
            ],
            [
                'number' => 8,
                'discipline' => 'Физика',
                'department' => 'Физики',
                'total_hours' => 324,
                'auditory_hours' => 194,
                'lectures' => 106,
                'labs' => 88,
                'practicals' => 0,
                'self_work' => 130,
            ],
            [
                'number' => 9,
                'discipline' => 'Основы электротехники и электроники',
                'department' => 'ИС',
                'total_hours' => 108,
                'auditory_hours' => 72,
                'lectures' => 36,
                'labs' => 18,
                'practicals' => 18,
                'self_work' => 36,
            ],
            [
                'number' => 10,
                'discipline' => 'Численные методы в информатике',
                'department' => 'ИС',
                'total_hours' => 189,
                'auditory_hours' => 89,
                'lectures' => 36,
                'labs' => 36,
                'practicals' => 17,
                'self_work' => 100,
            ],
            [
                'number' => 11,
                'discipline' => 'Методы исследования операций',
                'department' => 'ИС',
                'total_hours' => 216,
                'auditory_hours' => 104,
                'lectures' => 52,
                'labs' => 35,
                'practicals' => 17,
                'self_work' => 112,
            ],
        ];
    }
}
?>
